---

# Web server configuration
# -----------------------------------------------------------------------------

# The domain name that you've registered for the target webserver
domain_name: "{{ inventory_hostname }}"

# The Labs Engine container name defined in docker-compose.yml
docker_container_name: labs-engine

docker_install_compose: false
docker_compose_version: "2.29.2"

# If you don't want SSL certs, just flip this:
certbot_ssl: true
certbot_domain: "{{ domain_name }}"
certbot_renew_email: "{{ vault_admin_email }}"

# 4 web workers should be plenty - increase for machines with >2 CPUs
gunicorn:
  web_workers: 4


# Labs Engine configuration
# -----------------------------------------------------------------------------

django_secret_key: "{{ vault_django_secret_key }}"

# For manual manipulation of the database
skip_database_migration: false

# Git clone here
project_root: /srv/labs-engine

# This is where server conf files (nginx/gunicorn) will be created
config_root: "/srv/config"

create_directories:
  - "{{ config_root }}"
  - "{{ django_root }}/app/media"
  - "{{ django_root }}/app/logs"
  - "{{ temp_dir }}"

# Admin user login for the web admin
admin_user:
  first_name: admin
  last_name: admin
  email: "{{ vault_admin_email }}"
  password: "{{ vault_admin_password }}"

smtp:
  hostname: mail.smtp2go.com
  port: 587
  username: "{{ vault_smtp_username }}"
  password: "{{ vault_smtp_password }}"
  from_address: noreply@usegalaxy.org.au
  to_address: help@genome.edu.au
  use_tls: true

slack:
  api_key: "{{ vault_slack_api_key }}"
  channel_id: "{{ vault_slack_channel_id }}"
  mention_user_id: "{{ vault_slack_mention_user_id }}"

github_api_token: "{{ vault_github_api_token }}"

# Override log levels for specific loggers
# Value must be one of DEBUG, INFO, WARNING, ERROR, CRITICAL
django_log_levels:
  console: INFO
  cache: DEBUG

django_sentry_dns: "{{ vault_sentry_dns }}"
