---
- hosts: webservers
  remote_user: ubuntu
  become: true
  vars_files:
    - group_vars/VAULT
    - group_vars/webservers.yml
    - host_vars/labs.usegalaxy.org.au.yml
  roles:
    - role: geerlingguy.docker
      tags: init
    - role: bashrc
      tags: init
    - role: galaxy_labs_engine
      tags: always
