# Generated by Django 5.0.7 on 2026-01-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(help_text='Name of the lab visited', max_length=255)),
                ('datetime', models.DateTimeField(help_text='Timestamp of the visit')),
            ],
            options={
                'verbose_name': 'Lab Visit',
                'verbose_name_plural': 'Lab Visits',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='ToolUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(help_text='Name of the lab where tool was used', max_length=255)),
                ('tool_id', models.CharField(help_text='Full tool ID from Galaxy', max_length=512)),
                ('datetime', models.DateTimeField(help_text='Timestamp of the tool usage')),
            ],
            options={
                'verbose_name': 'Tool Usage',
                'verbose_name_plural': 'Tool Usages',
                'ordering': ['-datetime'],
            },
        ),
    ]
