# Generated by Django 5.0.7 on 2026-01-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_labvisit_toolusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolusage',
            name='tool_name',
            field=models.CharField(blank=True, default='', help_text='Parsed tool name for display', max_length=512),
        ),
    ]
