name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
    paths:
      - Dockerfile
      - requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    concurrency:
      group: docker-build-group
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_IMAGE }}:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_IMAGE }}:latest
